Ensure only one CSR in all_versions_invalid.json is invalid
all_versions_invalid.json is used in the
factory_csr_one_invalid_csr_of_multiple_fails test.

The removed CSRs were failing on the following error:

Error: Invalid root key
Caused by: disallowed labels should be empty: [...]

Bug: 419755369
Bug: 420613245
Test: atest --host hwtrust_cli_tests hwtrust_tests libhwtrust_tests
Change-Id: I6924df9b3e9da947f5b3a570e201f3bfa11894b7