Fix warnings for Rust 1.85.1 in tools/security
```
FAILED: out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy
ANDROID_RUST_VERSION=1.85.1 out/host/linux-x86/bin/rustc_wrapper prebuilts/rust/linux-x86/1.85.1/bin/clippy-driver --emit metadata -o out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy --emit dep-info=out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy.d.raw tools/security/remote_provisioning/hwtrust/src/lib.rs --extern openssl=out/soong/.intermediates/external/rust/crates/openssl/libopenssl_static/linux_glibc_x86_64_rlib_rlib-std/libopenssl_static.rlib --extern anyhow=out/soong/.intermediates/external/rust/android-crates-io/crates/anyhow/libanyhow/linux_glibc_x86_64_rlib_rlib-std/libanyhow.rlib --extern base64=out/soong/.intermediates/external/rust/android-crates-io/crates/base64/libbase64_rust/linux_glibc_x86_64_rlib_rlib-std/libbase64_rust.rlib --extern chrono=out/soong/.intermediates/external/rust/android-crates-io/crates/chrono/libchrono/linux_glibc_x86_64_rlib_rlib-std/libchrono.rlib --extern ciborium=out/soong/.intermediates/external/rust/android-crates-io/crates/ciborium/libciborium/linux_glibc_x86_64_rlib_rlib-std/libciborium.rlib --extern clap=out/soong/.intermediates/external/rust/android-crates-io/crates/clap/libclap/linux_glibc_x86_64_rlib_rlib-std/libclap.rlib --extern coset=out/soong/.intermediates/external/rust/android-crates-io/crates/coset/libcoset/linux_glibc_x86_64_rlib_rlib-std/libcoset.rlib --extern hex=out/soong/.intermediates/external/rust/android-crates-io/crates/hex/libhex/linux_glibc_x86_64_rlib_rlib-std/libhex.rlib --extern itertools=out/soong/.intermediates/external/rust/android-crates-io/crates/itertools/libitertools/linux_glibc_x86_64_rlib_rlib-std/libitertools.rlib --extern serde_json=out/soong/.intermediates/external/rust/android-crates-io/crates/serde_json/libserde_json/linux_glibc_x86_64_rlib_rlib-std/libserde_json.rlib --extern thiserror=out/soong/.intermediates/external/rust/android-crates-io/crates/thiserror/libthiserror/linux_glibc_x86_64_rlib_rlib-std/libthiserror.rlib --extern std=prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7db8ef8b6d15f2e7.rlib -L out/soong/.intermediates/external/boringssl/libbssl_sys_static/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/bitflags/libbitflags/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/cfg-if/libcfg_if/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/foreign-types/libforeign_types/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/libc/liblibc/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/once_cell/libonce_cell/linux_glibc_x86_64_rlib_rlib-std/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/openssl-macros/libopenssl_macros/linux_glibc_x86_64/ -L prebuilts/rust/linux-x86/1.85.1/lib/rustlib/x86_64-unknown-linux-gnu/lib -L out/soong/.intermediates/external/boringssl/libbssl_sys_raw_staticfns/linux_glibc_x86_64_static/ -L out/soong/.intermediates/external/boringssl/libcrypto_static/linux_glibc_x86_64_static/ -L out/soong/.intermediates/external/boringssl/libssl_static/linux_glibc_x86_64_static/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/foreign-types-shared/libforeign_types_shared/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/num-traits/libnum_traits/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/serde/libserde/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/serde_derive/libserde_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/ciborium-io/libciborium_io/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/ciborium-ll/libciborium_ll/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/half/libhalf/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/clap_builder/libclap_builder/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/clap_derive/libclap_derive/linux_glibc_x86_64/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/anstyle/libanstyle/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/clap_lex/libclap_lex/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/strsim/libstrsim/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/ciborium/libciborium/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/either/libeither/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/itoa/libitoa/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/memchr/libmemchr/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/ryu/libryu/linux_glibc_x86_64_rlib_rlib-std/ -L out/soong/.intermediates/external/rust/android-crates-io/crates/thiserror-impl/libthiserror_impl/linux_glibc_x86_64/ -Z unstable-options -Z stack-protector=strong -Z remap-cwd-prefix=. -C debuginfo=2 -C opt-level=3 -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color=always -Z dylib-lto -Z link-native-libraries=no -Z force-unstable-if-unmarked --cfg soong -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib32 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/x86_64-linux/lib64 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/lib/gcc/x86_64-linux/4.8.3 -Lprebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/lib  -C relocation-model=pic -A deprecated -A unknown_lints -D missing-docs -D warnings -D unsafe_op_in_unsafe_fn --edition=2021 -C metadata=libhwtrust --crate-type=rlib --crate-name=hwtrust --target=x86_64-unknown-linux-gnu --sysroot=/dev/null -C codegen-units=1 -Zallow-features="" -A clippy::disallowed_names -A clippy::empty_line_after_doc_comments -A clippy::type-complexity -A clippy::unnecessary_fallible_conversions -A clippy::unnecessary-wraps -A clippy::unusual-byte-groupings -A clippy::upper-case-acronyms -D clippy::undocumented_unsafe_blocks && grep ^out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy: out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy.d.raw > out/soong/.intermediates/tools/security/remote_provisioning/hwtrust/libhwtrust/linux_glibc_x86_64_rlib_rlib-std/libhwtrust.rlib.clippy.d
error: this `map_or` can be simplified
   --> tools/security/remote_provisioning/hwtrust/src/cbor/rkp/device_info.rs:229:13
    |
229 |             self.vbmeta_digest.as_ref().map_or(true, |d| !d.iter().all(|b| *b == 0u8)),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use is_none_or instead: `self.vbmeta_digest.as_ref().is_none_or(|d| !d.iter().all(|b| *b == 0u8))`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
    = note: `-D clippy::unnecessary-map-or` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::unnecessary_map_or)]`

error: aborting due to 1 previous error
```

Bug:
Test: m rust
Flag: EXEMPT refactor
Change-Id: Ied4ad40522dbec011099f743f587314cd0ec40ae